chore remove dead links
falconry/falconry.github.io pull request #29
Opened 2020-12-20 22:36 UTC by CaselIT

- https://www.likalo.com/ is no longer reachable
- https://www.pnk.sh/python-falcon seems to no longer exist. https://www.pnk.sh is still up

2020-12-20 22:38 UTC, vytas7 requested changes
Let's check both with our sponsors in question first.

2020-12-20 22:39 UTC, CaselIT commented
wanted to ask on gitter

2021-02-21 23:00 UTC, vytas7 commented
Now that https://github.com/falconry/falcon/pull/1867 has landed, we need to shovel those snippets into the website too.

2021-02-22 17:15 UTC, CaselIT commented
it may be best to close this and open another with the updated links, probably after #31 is merged

2021-03-24 22:39 UTC, CaselIT commented
@kgriffs we still have some links that are dead, I'll let you handler them

2021-04-01 20:11 UTC, vytas7 commented
Is there anything left to be done in this issue? AFAICT @kgriffs has now revised the sponsor list here on the website too.

2021-04-01 21:25 UTC, CaselIT commented
don't think so

2021-04-01 21:25 UTC, closed without merging